name: CI-BlackDuck-Basic
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Black Duck Scan
        uses: blackduck-inc/black-duck-security-scan@v2.0.0
        
        ### Configure DETECT environment variables
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          BLACKDUCK_TRUST_CERT: true
          
        with:
          ### SCANNING: Required fields
          blackducksca_url: https://4.157.105.116
          blackducksca_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackducksca_fixpr_enabled: true
          blackducksca_fixpr_filter_severities: ALL
          github_token: ${{ secrets.GITHUB_TOKEN }}
          blackducksca_scan_full: false
          blackducksca.automation.prComment: true
         
          ### SCANNING: Optional fields
          # blackduck_scan_failure_severities: 'BLOCKER,CRITICAL'
          
          ### FIX PULL REQUEST CREATION: Uncomment below to enable
          # blackduck_fixpr_enabled: true
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when Fix PRs is enabled
          
          ### PULL REQUEST COMMENTS: Uncomment below to enable
          # blackduck_prcomment_enabled: true 
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments is enabled

