name: CI-BlackDuck-SCA

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tags:
        description: "BlackDuck release tag:"
        required: true
        type: string

jobs:
  blackduck_scan:
    runs-on: [ubuntu-latest]

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Black Duck SCA Full Scan
        id: black-duck-full-scan
        if: ${{ github.event_name != 'pull_request' }}
        uses: blackduck-inc/black-duck-security-scan@6ee400ee2502a366bdff13cddae76bbde804fd20 #v2.1.1

        ### Use below configuration to set specific detect environment variables
        env:
          DETECT_PROJECT_NAME: "GenAI"
          # DETECT_PROJECT_NAME: "${{ github.event.repository.name }}"
          # DETECT_PROJECT_VERSION_NAME: ${{ inputs.tags }}
          DETECT_PROJECT_VERSION_NAME: "centralservices_1.1.1"
        with:
          blackducksca_url: ${{ vars.BLACKDUCK_SERVER_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCK_ACCESS_TOKEN }}
          blackducksca_scan_full: true

          ### Accepts Multiple Values
          blackducksca_scan_failure_severities: "BLOCKER,CRITICAL"

          ### Arbitrary product-related CL arguments
          detect_search_depth: 10

      - name: Black Duck SCA PR Scan
        id: black-duck-pr-scan
        if: ${{ github.event_name == 'pull_request' }}
        uses: blackduck-inc/black-duck-security-scan@6ee400ee2502a366bdff13cddae76bbde804fd20 #v2.1.1

        ### Use below configuration to set specific detect environment variables
        env:
          DETECT_PROJECT_NAME: "GenAI"
        with:
          blackducksca_url: ${{ vars.BLACKDUCK_SERVER_URL  }}
          blackducksca_token: ${{ secrets.BLACKDUCK_ACCESS_TOKEN  }}
          blackducksca_scan_full: false

          ### Below configuration is used to enable automatic pull request comment based on Black Duck SCA scan result
          blackducksca_prComment_enabled: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

          ### Arbitrary product-related CL arguments
          detect_search_depth: 10
          detect_args: '--detect.diagnostic=true --detect.detector.search.depth=10'
          

