name: CI-BlackDuck-Basic
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Black Duck Scan
        uses: synopsys-sig/synopsys-action@v1.8.0
        
        ### Configure DETECT environment variables
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          
        with:
          ### SCANNING: Required fields
          blackduck_url: https://52.255.229.70
          blackduck_token: ZDdhODgyOTYtYmM2ZC00OTMyLWI4MjQtZDg5MmZmMWMxNjY3OjMzNTE0MGZmLTZlZTYtNDRiOC1iYzBhLTBkODJlY2UyNWVlMw==
         
          ### SCANNING: Optional fields
          # blackduck_scan_failure_severities: 'BLOCKER,CRITICAL'
          
          ### FIX PULL REQUEST CREATION: Uncomment below to enable
          # blackduck_fixpr_enabled: true
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when Fix PRs is enabled
          
          ### PULL REQUEST COMMENTS: Uncomment below to enable
          # blackduck_prcomment_enabled: true 
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments is enabled

