name: GitHub Actions Demo
on: [push]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Synopsys Deect
      uses: synopsys-sig/detect-action@v0.3.4
      env:
        NODE_TLS_REJECT_UNAUTHORIZED: false
        DETECT_DIAGNOSTIC: true
        SPRING_APPLICATION_JSON: '{"detect.project.name":"FALSE"}'
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 8.10.0
          blackduck-url: https://saastest.app.blackduck.com
          blackduck-api-token: Y2E4NWQ0NTMtZmVkZi00NzcyLThlZWQtM2U3YzVjMWYzZDVhOjg4Njg4YjJhLTcwNDgtNGVkNS1hMjIxLWQwNWU4NzQ5YWRmYQ==
